### ISSUE TITLE
nullreference Exceptions => UIImage.FromBundle()

### ISSUE THREAD

**Issue by MrBasque** [Prin53/Xamarin.iOS.PKHUD#1]
Thanks for this Port, was waiting for this.

I gave it a try, but I stumbled on a few implementation problems, so unfortunately it's not usageble/ready for my project so far.

The biggest issue I have right now is:

When the package is referenced in my project (without typing any code), I get nullreference Exceptions whenever I call UIImage.FromBundle("any-assetcatalog-image") anywhere in my code.
(When I remove the package, these problems dissapear)

Regards,
Bas

**Comment by prin53** [comment]
@MrBasque, thank you for reporting and sorry for a long answer. I fixed the issue with images on #2. It works on my test projects. Could you please check it?
